# 系统配置
system:
  db_type: ""
  router_prefix: /api/v1

# jwt 配置
jwt:
  signing_key: f11a18af934b4b758de6f7e9e7c239ac
  expiration_time: 72h
  buffer_time: 24h
  issuer: server

# 验证码配置
captcha:
  long: 6 # 验证码字符长度
  img_width: 240 # 验证码图片宽度
  img_height: 80 # 验证码图片高度
  open_captcha: 3 # 0 代表一直开启，大于 0 代表限制次数
  open_captcha_timeout: 5m # open-captcha 大于 0 时才生效

mysql:
  host: "" # 地址
  port: "" # 端口
  db_name: "" # 数据库名称
  username: "" # 账号
  password: "" # 密码
  max_idle_conns: 10 # 最大空闲连接数
  max_open_conns: 100 # 最大连接数
  conn_max_lifetime: 10s # 连接存活时间
  config: charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local
  log_mode: error # 是否开启 gorm 全局日志
  log_zap: false # 是否打印日志到 zap
  prefix: sys_

zap:
  level: info
  format: console
  director: log
  encode_level: LowercaseColorLevelEncoder
  log_in_console: true

# 黑名单
black_domain:
  - "gov.cn"
  - "edu.cn"

# 邮件配置
mail:
  smtp_server: "smtp.qq.com" # 邮件服务器
  smtp_port: "587" # 邮件服务器 端口
  smtp_from: "784288604@qq.com" # 邮件发送用户
  smtp_password: "wbmdmermwwftbeaf" # 密码

fofa:
  url: https://fofa.info/
  mail: 784288604@qq.com
  key: 10214b2f11a229ac2c48f02bf188ab29