captcha:
    long: 6
    img_width: 240
    img_height: 80
    open_captcha: 3
jwt:
    signing_key: f11a18af934b4b758de6f7e9e7c239ac
    expiration_time: 72h
    buffer_time: 24h
    issuer: server
mysql:
    host: 121.37.217.131
    port: "3306"
    db_name: rn
    username: root
    password: root
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 10s
    config: charset=utf8mb4&parseTime=True&loc=Local
    log_mode: error
    log_zap: false
system:
    db_type: mysql
    router_prefix: /api/v1
zap:
    level: info
    format: console
    director: log
    encode_level: LowercaseColorLevelEncoder
    log_in_console: true
